fusionpbx/fusionpbx-install.sh

debian/resources/fail2ban/jail.package, debian/resources/fail2ban/jail.source, debian/resources/fail2ban/nginx-404.conf, debian/resources/fail2ban/nginx-dos.conf
=> Add NGINX 404 and DOS filters

README.md, debian/resources/iptables.sh
This adds some basic rules to help protect against script-kiddies
=> Add some essential rules

debian/resources/iptables.sh
Updated iptables rules to make dropping known bots easier
included ssl ports as well
added comments to rules where appropriate
=> Enhance debian iptables

debian/resources/switch/package-permissions.sh
=> BugFix permissions

README.md
Install ca-certificates just in case this is a very bare debian install as git will fail without it.
=> Install ca-certificates

README.md, debian/install.sh, install-linux.sh
Added bootstrap installer to help simplify the install
Checks for root
Checks what OS (in a way that can be expanded)
If > Debian 8
- Install Git
- Fetch the rest of the installer
- Start the Install passing though command line options
=> Enhance Add bootstrap installer

debian/resources/iptables.sh
added a couple more persistent bots
=> Enhance-Add new bots

debian/install.sh, debian/resources/postgres.sh
remove path on systemctl as it should rely on path as it could be in
/sbib/ on some systems
=> BugFix-make relative paths work

debian/resources/switch/source-release.sh, debian/resources/switch/source/freeswitch.service
moved version number up to match release (1.6.9)
added freeswitch user
added ln to fs_cli
added freeswitch.service
=> BugFix-source install updates

debian/install.sh, debian/resources/colors.sh, install.sh
added colour support in a way that will not screw up the console if
colour support is not available
Used US spelling ;p
If approved will add to remaining scripts
=> Enhance Add colours

debian/resources/nginx/fusionpbx
=> rewrite rule fix for yealink common

debian/resources/switch/source-release.sh
fetch the latest version automatically
=> Enhance-Get Version automatically

debian/install.sh, debian/resources/php.sh
update the post_max_size to 32M during the install
In response to feedback on https://github.com/fusionpbx/fusionpbx/pull/1715
=> Enhance-Add php config

debian/install.sh
remove --use-switch-package-unofficial-arm
when arm detected automatically use the unoffcial repos
=> Enhance-use unofficial repo when arm detected automatically

debian/resources/nginx/fusionpbx
Correct polycom rewrite rule (port 80 and 443)
=> Correct polycom rewrite rule

debian/resources/nginx/fusionpbx
Aastra phones wont load with out first getting aastra.cfg
=> Updated aastra rewrite rule

debian/install.sh, debian/resources/arguments.sh, debian/resources/fusionpbx.sh, debian/resources/switch/package-release.sh
moved command line argument processing to a separate script so it can be
shared
added --use-system-master to allow user to use master branch instead of
detected stable
=> Added Branch support

debian/resources/fail2ban.sh, debian/resources/iptables.sh, debian/resources/nginx.sh, debian/resources/php.sh
enable colours in more scripts
change fail2ban.s to use arguments.sh to initialize it's variables
=> Enhance-More Colours

debian/resources/fail2ban.sh, debian/resources/nginx.sh
some relative paths needed to be updated when chdir was added
=> BugFix Relative paths

centos/install.sh, centos/resources/arguments.sh, centos/resources/backup/fusionpbx-backup.sh, centos/resources/colors.sh, centos/resources/fail2ban.sh, centos/resources/fail2ban/freeswitch-404.conf, centos/resources/fail2ban/freeswitch-dos.conf, centos/resources/fail2ban/freeswitch-ip.conf, centos/resources/fail2ban/freeswitch.conf, centos/resources/fail2ban/fusionpbx.conf, centos/resources/fail2ban/jail.local, centos/resources/fail2ban/nginx-404.conf, centos/resources/fail2ban/nginx-dos.conf, centos/resources/finish.sh, centos/resources/firewalld.sh, centos/resources/fusionpbx.sh, centos/resources/fusionpbx/config.php, centos/resources/nginx.sh, centos/resources/nginx/fusionpbx, centos/resources/php.sh, centos/resources/postgres.sh, centos/resources/sslcert.sh, centos/resources/switch/conf-copy.sh, centos/resources/switch/package-permissions.sh, centos/resources/switch/package-release.sh, centos/resources/switch/package-systemd.sh, centos/resources/switch/source/etc.default.freeswitch, centos/resources/switch/source/freeswitch.service.package, centos/resources/switch/source/freeswitch.service.source
Main install.sh still to be updated to detect OS version, documentation to advise to run the install.sh within the centos folder to install on centos.
=> CentOS 7 Installer

debian/resources/nginx.sh, debian/resources/postgres.sh
Add PHP 7 and Postgres 9.6 for ARM.
Tested working
=> Update for ARM

centos/resources/nginx/fusionpbx, debian/resources/nginx/fusionpbx, devuan/resources/nginx/fusionpbx, freebsd/resources/fusionpbx/fusionpbx, freebsd/resources/nginx/fusionpbx.conf
Update rewrite rules for:
* Grandstream phonebook.xml
* Grandstream wave - by extension not mac
* Add Vtech
=> Add Grandstream and Vtech rewrites

centos/resources/reset_admin_password.sh, debian/resources/reset_admin_password.sh, devuan/resources/reset_admin_password.sh, freebsd/resources/reset_admin_password.sh
will look for all instances of system_username from config.sh in the database and update it's password
=> Enhance - add reset_admin_password.sh

debian/resources/switch/package-release.sh
=> Only remove MOH for x86

centos/resources/environment.sh, debian/resources/environment.sh, devuan/resources/environment.sh
When there is a error with the enviroment report more information
fixes for the centos script that had some parts wrong
=> Enhance - report more on error in enviroment.sh

debian/resources/nginx/fusionpbx
Fixed some minor errors in the rewrite rule for Grandstream phonebook.
=> Fix rewrite for Grandstream phonebook

README.md
Updated references to Debian 8 to show Debian 9 as it was confusing some people.
=> Updated README.md with Debian 9 details

README.md
Just a handful of minor edits to the readme.
=> Update Devuan codename, minor revising for readability

centos/resources/iptables.sh, debian/resources/iptables.sh
Removed the iptables rule containing --string "system" as is can cause issues with legitimate SIP traffic from clients with user agents such as "3CXPhoneSystem"
=> Iptables update

windows/install.ps1
https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5#36454717
https://www.imperialviolet.org/2014/12/08/poodleagain.html
=> Comment out weak security ciphers

debian/resources/nginx/fusionpbx
Added a rewrite rule for Snom phones
=> Add rewrite for Snom phones

debian/resources/postgresql.sh
If condition always evaluated to true.
=> If condition always evaluated to true

ubuntu/resources/config.sh, ubuntu/resources/nginx.sh, ubuntu/resources/php.sh, ubuntu/resources/switch/source-release.sh, ubuntu/resources/switch/source/etc.default.freeswitch.source
Bump php version to 7.4, removed libvpx5.
=> Ubuntu 20.04

ubuntu/resources/backup/fusionpbx-maintenance
make the maintenance script more easily changed. Disable deletions by default.
=> Add options

debian/resources/switch/source-release.sh
Adds the ability to build mater branch by setting the existing variable `$switch_branch` to `master` in config.sh
=> Add ability to build master branch

freebsd/resources/switch/source-release.sh
Tested on HardenedBSD 14-CURRENT
I'm honestly not sure how the script ever worked without the missing cd commands?
=> Update FreeBSD install script (for release, anyways)

debian/resources/postgresql/create.sh, freebsd/resources/config.sh, freebsd/resources/fail2ban.sh, freebsd/resources/fail2ban/freeswitch-dos.conf, freebsd/resources/postgresql.sh, freebsd/resources/switch/package-release.sh
A few fixes and tweaks to allow FusionPBX to be deployed on FreeBSD 14 using the scripts.
=> Fixes to allow deployment on FreeBSD 14

debian/resources/backup/fusionpbx-maintenance
fix spacing for variable assignment
=> fix spacing for variable assignment

debian/resources/backup/fusionpbx-maintenance
v_event_guard_logs
v_user_logs
v_xml_cdr_flow
v_xml_cdr_json
v_xml_cdr_logs
=> add new log tables and new cdr tables

debian/resources/letsencrypt.sh, devuan/resources/letsencrypt.sh
updated the install script to have the new path for dehydrated: https://github.com/dehydrated-io/dehydrated.git
=> updated the repo for dehydrated

centos/resources/nginx/fusionpbx, debian/resources/nginx/fusionpbx, devuan/resources/nginx/fusionpbx, freebsd/resources/nginx/fusionpbx.conf, ubuntu/resources/nginx/fusionpbx
Fixed the Avaya rewrites and added the rewrites to other distros
=> Avaya rewrite rules added for all distros

debian/resources/backup/fusionpbx-maintenance
- updated tables that were not deleting
- updated user log table IF statement variable name
- changed section comments to echo so it is easier to know what is being deleted if running manually. includes number of days
=> fix tables not deleting and added echoing
