- debian/resources/fusionpbx.sh
- debian/resources/switch/package-release.sh
The Freeswitch all package forces the installation of freeswitch-mod-voicemail and this module has a dependency to install a mailserver like Postfix otherwise Freeswitch will not install.  The installation of any mailserver can be a major security risk.  
Therefore I have made the changes to allow the required packages to be installed without the freeswitch-mod-voicemail since this is no required by FusionPBX as far as I am aware.
There are a few other optional packages that I have added.  I also included the ssl-cert dependency which provides the snakeoil cert.
Best Regards
Errol
> Install Freeswitch packages

- debian/install.sh
- install.sh
encourage users to submit the output of lsb_release as an issue when
that test fails, this should allow contributors not in irc at the time
of the problem to see the information
Add CPU and OS bit checking which can be disabled with --no-cpu-check
> Enhance-Add OS-CPU bit checking

- debian/resources/switch/source-release.sh
source-release was cding out of the base dir so was causing following
commands to fail as they were no longer correctly relative
Added store and return for the working directory
> BugFix-source-release

- debian/install.sh
fix an issue reported in IRC with cubox-i4 not detecting the CPU correctly due to the test needing to be stringified and the && test needing to be separated by bracketing
> BugFix-Arm compatibility

- debian/install.sh
- install.sh
If lsb_release -i is Raspbian report as Debian to os_check
reorganised CPU/OS checks to be more in depth and separate detects from checks
> Enhance-Add Raspbian Support

- debian/resources/switch/source-release.sh
due to sort treating the list as text even though numeric anything above
10 was effectively ignored (until version 90)
> BugFix-When source version above 9

- debian/install.sh
- debian/resources/arguments.sh
- debian/resources/fusionpbx.sh
- debian/resources/switch/package-release.sh
sourcing of one script into another is proving inconsistent depending on which script was originally called due to $0 doesn't get updated
> BugFix-Resource sourcing

- debian/install.sh
- debian/resources/nginx.sh
- debian/resources/nginx/fusionpbx
- debian/resources/php.sh
test is passed with Ubuntu 16.04 amd64
needs to change apt sources to 
1) http://files.freeswitch.org/repo/ubuntu/freeswitch-1.6/dists/xenial/ - no packages here
2) http://files.freeswitch.org/repo/ubuntu-1604/freeswitch-unstable/dists/xenial/ - to be checked
``
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1FDDF413C2B201E5
``
``
$ gpg --keyserver keyserver.ubuntu.com --recv-keys 1FDDF413C2B201E5
``
gpg: requesting key C2B201E5 from hkp server keyserver.ubuntu.com
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key C2B201E5: public key "Freeswitch Commercial Package Repo (https://repo.freeswitch.com) <wking@freeswitch.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
``
$ gpg --verbose --verify …
> transition from php5* packages to php-7.0*

- debian/install.sh
- debian/resources/arguments.sh
- debian/resources/nginx.sh
- debian/resources/php.sh
Example usage
``
./install.sh --use-php5-package
``
> Fix to issue #76 - Use php5 for some dists with new command-line switch

- freebsd/install.sh
- freebsd/resources/nginx.sh
With regards to the removing of portsnap update, this appears to fail when the ports where installed during the FreeBSD install.
It complains with: "/usr/ports was not created by portsnap.
You must run 'portsnap extract' before running 'portsnap update'."
This means that the needed 7.1 stuff never gets installed.
The other part of the pull request pulls in postgres 9.6 and php 71 before compiling the two needed modules. This means that rather than compiling postgres and php 71, the packages can be used instead.
> Making install easier

- centos/resources/nginx/fusionpbx
- debian/resources/nginx/fusionpbx
- devuan/resources/nginx/fusionpbx
- freebsd/resources/fusionpbx/fusionpbx
update configuration to allow the core/upgrade/install.php to have the
same read_timeout in nginx as it has in php execution time.
This should prevent the nginx timeout error when a upgrade takes longer
than 60 seconds (the deafult in nginx)
> BugFix core/upgrade/install.php timeout

- debian/resources/postgresql/dsn.sh
Check .db exists before deleting. Prevents error output if .db file doesn't exist.
> Enhance - dsn.sh rm file check

- debian/resources/switch/package-systemd.sh
- debian/resources/switch/source-systemd.sh
This will get Freeswitch working on OpenVZ containers, but FusionPBX still isn't properly set up due to a few OpenVZ quirks causing issues with these scripts. May want to use these changes on other distros too, namely CentOS.
> Added minimal OpenVZ support.

- debian/resources/config.sh
- debian/resources/nginx.sh
I kept stubbing my toe on this when using acme.sh, figured making it switchable might be a good idea. Might add acme.sh support if there is any interest.
> Easy disabling of LetsEncrypt folders

- debian/resources/fail2ban/freeswitch-dos.conf
Default fail2ban DoS ruleset looks for auth challenges, but auth challenges can be either successful or unsuccessful. Default rule causes problems with larger environments with many registered devices as they have many successful auth challenges with short registration periods.
By the time auth challenges can be made successfully in volume, it's far too late to be worrying about a DoS or brute force attempt. Rule change here will reduce false positives while still providing same level of useful protection.
Maybe also consider reducing maxretry count or increasing findtime in jail.local to catch true failed auth brute force or DoS attempts more easily in conjunction with above change.
This will be more sensitive in detection and should carry lower false positive rate.
> Ban on auth failure instead of challenge

- README.md
- centos/resources/fail2ban/jail.local
- debian/resources/fail2ban/jail.local
- devuan/resources/fail2ban/jail.local
- freebsd/resources/fail2ban/jail.local
Nginx-dos was triggered by auto-refresh behavior in FusionPBX when on certain pages like Active Calls, this permanent ban was easy to hit if Active Calls was open in more than 1 tab/window. This pull request disables this rule by default, and makes its ban time consistent across OSes that have Fail2ban installed when running the scripts from this repository.
> Changed Fail2ban settings, updated Readme

- centos/resources/php.sh
For a clean install of Centos 7 and using the installer php-fpm get the
permission error
"unix:/var/run/php-fpm/php-fpm.sock failed (13: Permission denied) while
connecting to upstream"
This patch the correct group and user to run php-fpm process.
> Bugfix: Fix  the user/group  for /etc/php-fpm.d/www.conf

- debian/resources/backup/fusionpbx-maintenance
- devuan/resources/backup/fusionpbx-maintenance.sh
- ubuntu/resources/backup/fusionpbx-maintenance
This allows fusionpbx-maintenance to also clean up Fax Logs (90 days)
> Fax Logs Clean up

- debian/resources/letsencrypt.sh
The sed entries to update the config file was creating the following issues: 1) It was creating duplicate config files, the second has a trailing space. 2) The email variable was not passed to the config file. 3) removing the leading # from WELLKNOWN does not require the file path as it does not change. This shortened command may eliminate the creating of two config files.
> Update sed entries in debian/letsencrypt.sh file

- debian/resources/postgresql/node.sh
I noticed fail2ban was not running after node.sh completed. 
It stops after iptables-persist. I added 'systemctl restart fail2ban" to have it running properly
> Update node.sh to restart fail2ban if Yes is selected to update iptables rules

- windows/install.ps1
It seems like on Windows Server 2016 or maybe other Windows OSs powershell uses TLS 1.0 by default and the sources have different tls versions. So this will make the script work without throwing those errors.
> Fix Invoke-WebRequest Fails with SSL/TLS Secure Channel fails

- ubuntu/resources/config.sh
- ubuntu/resources/letsencrypt.sh
- ubuntu/resources/switch/source-release.sh
I have installed and tested this on Ubuntu 18.04 with no issue except for runtime sound_prefix issues for non-en/us/callie sounds. Presume this is some kind of caching/fusionpbx issue
> Update ubuntu install config for 18.04

- freebsd/install.sh
- freebsd/resources/fail2ban.sh
- freebsd/resources/php.sh
1. Typo in the install.sh (missing space before "]").
2. python 2.7 is being deprecated, most of the packages including fail2ban have 3.7 version now and those that depend on Python install 3.7 by default. With the current scheme one ends up with both 2.7 and 3.7 installed.
3. There is unneded "cd" in one of the scripts, which causes error message to be printed out (php.sh is included from nginx.sh and the latter does cd resources as the first step already).
00:03:45.521  Cloning into '/usr/local/www/fusionpbx'...
Updating files: 100% (4705/4705), done.
00:03:55.135  + [ .true '=' .true ]
00:03:55.135  + resources/nginx.sh
00:03:55.135  + pwd
00:03:55.135  /tmp/fusionpbx-install.sh/freebsd
00:03:55.135  + dirname resources/nginx.sh
00:03:55.135  + cd resources
00:03:55.135  + . …
> Few small freebsd fixes

- centos/resources/switch/package-release.sh
Previous version of this script pulled FreeSWITCH 1.6, but there is an official RPM package available for 1.10.3.  I have tested this with my own system and haven't encountered problems.
> Install FreeSWITCH 1.10.3 on CentOS 7

- debian/resources/ioncube.sh
- debian/resources/iptables.sh
- debian/resources/nginx.sh
- debian/resources/php.sh
- debian/resources/postgresql.sh
- debian/resources/switch/source-release.sh
FusionPBX will now install and run on Debian 11. 
Support for Debian 11 should be considered BETA. Use at your own risk!
Modified multiple install scripts for Debian 11 "Bullseye" support now that FreeSWITCH 1.10.7 packages officially support it. PostgreSQL was tested with 9.4 for BDR.
Changes made to the following files:
* /debian/resources/ioncube.sh
* /debian/resources/iptables.sh
* /debian/resources/nginx.sh
* /debian/resources/php.sh
* /debian/resources/postgresql.sh
* /debian/resources/switch/source-release.sh
Now using PHP 7.4 as it is the default version in Bullseye.
> Add Preliminary Debian 11 "Bullseye" Support

- debian/resources/config.sh
- debian/resources/iptables.sh
- debian/resources/php.sh
- debian/resources/switch/source-release.sh
This commit is a WIP for Freeswitch 1.10.7 support on Debian 11.1 "Bullseye". It adds sofia-sip and spandsp as separate dependencies.
Install: ok!
To-Dos (same as in ubuntu-pr #378 )
~Adjust Fail2ban-Filters like described in https://www.pbxforums.com/threads/upgrade-to-1-10-7.5743/post-23063~
Regarding Fail2ban: https://www.pbxforums.com/threads/upgrade-to-1-10-7.5743/post-23160
Seems to work on my side without modification.
Testing functionality.
> [WIP] Debian Bullseye - Freeswitch 1.10.7

- ubuntu/resources/config.sh
- ubuntu/resources/switch/source-release.sh
This commit is a WIP for Freeswitch 1.10.7 support on Ubuntu 20.04. It adds sofia-sip and spandsp as separate dependencies.
Install: ok!
To-Dos: 
~Adjust Fail2ban-Filters like described in https://www.pbxforums.com/threads/upgrade-to-1-10-7.5743/post-23063~
Regarding Fail2ban: https://www.pbxforums.com/threads/upgrade-to-1-10-7.5743/post-23160
Testing functionality.
> [WIP] Ubuntu - Freeswitch 1.10.7

- debian/resources/nginx.sh
It doesn't seem to have any purpose. If someone knows the purpose feel free to update in a way that doesn't break the config
> comment out lines that breaks nginx config file

- debian/resources/config.sh
Added a new variable to config.sh "switch_token". A Personal Access Token is now needed to pull from the Community version of FreeSWITCH.  To generate one, please create an account at https://signalwire.com More info can be found here. https://freeswitch.org/confluence/display/FREESWITCH/HOWTO+Create+a+SignalWire+Personal+Access+Token
> FreeSWITCH Repo change

- debian/resources/switch/source/mod_pgsql.patch
We use pgsql14 and build from source on 1.10.7 was failing again for some reason. Updated the source code to match the current freeswitch master branch and it worked fine. Updated code these differences were made from can be found here:
https://github.com/signalwire/freeswitch/commit/92d2e0b1366297b8b8fe584cd398641edbf3e803
> Update mod_pgsql.c patch

- README.md
Hi, I saw that the repo has a folder for installing it on Ubuntu, but the README.md did not have such a command line to help users to copy and paste it quickly. So I added it. I am interested in installing this on a Raspberry Pi, so I also added this name with Ubuntu since I thing they are quite compatible.
> Add command line for installing on Ubuntu/Raspbian OS

- debian/resources/switch/source-permissions.sh
Make source-permissions.sh the same as package-permissions.sh, since the paths are the same.
> Source Switch Scripts - Updated source permissions script.

- debian/resources/switch/source-release.sh
Required for Advanced > Number Translations app.
> Enable mod_translate when building FreeSWITCH

- debian/resources/environment.sh
- debian/resources/switch/source-master.sh
- debian/resources/switch/source-release.sh
While SignalWire doesn't have aarch64 debs of FreeSWITCH, PostgreSQL.org and sury.org have debs of PgSQL & PHP for aarch64, respectively. Compiling FreeSWITCH from source works cleanly on aarch64, tested on both Armbian and stock Debian. So might as well remove the unsupported, unless there's another reason to not?
While we're add it, let's parallelize the makes, as it's dreadfully slow on most SBCs without it
> Remove unsupported error for aarch64 Linux

- debian/resources/php.sh
- debian/resources/postgresql.sh
- debian/resources/sngrep.sh
- debian/resources/switch/package-release.sh
- debian/resources/switch/repo.sh
- debian/resources/upgrade/php.sh
- devuan/resources/switch/package-release.sh
- ubuntu/resources/postgresql.sh
Adding key files to `/etc/apt/trusted.gpg.d/` is equivalent to the old method of apt-key add that appended to `/etc/apt/trusted.gpg` because while each key is an individual file for easier delete/add, the entire folder is trusted for any repository. Putting the keys into the `/etc/apt/keyrings/` folder as suggested by the documentation forces us to add the specific key to the deb entries instead of all keys being trusted automatically from the other folder. I did not make this change for older/unused/rarely used scripts, like the ones that don't even have the new signalwire access token updates.
I've also enabled to install sngrep from the official repository always instead of just on Jessie because debian is always significantly behind on the sngrep versions to the point where a major …
> Improve apt key security and always install sngrep from official

- debian/resources/finish.sh
Debian 12 doesn't always have crontab command available by default
> Install Cron on Debian

- debian/resources/backup/fusionpbx-maintenance
A couple of variables were not being called correctly (missing '$'). 
A couple of database connection strings were not consistent with the other connection strings.
> Fix calling variables and consistent database connections

- centos/resources/nginx/fusionpbx
- debian/resources/nginx/fusionpbx
- devuan/resources/nginx/fusionpbx
- freebsd/resources/nginx/fusionpbx.conf
- ubuntu/resources/nginx/fusionpbx
These changes add the necessary rewrite rules for snom phones to follow the same url as other phone manufacturers.
Below are some sample screen snippets of my `access.log`
These changes make a slight modification to an existing rule.
> Added nginx rewrites to fix snom provision url

- debian/resources/iptables.sh
Bookworm (12) is not accounted for in the iptables script. End up with an almost blank chain on install.
> Update iptables.sh for Debian 12

- debian/resources/backup/fusionpbx-backup
- debian/resources/backup/fusionpbx-maintenance
- debian/resources/finish.sh
- debian/resources/postgresql/dsn.sh
- debian/resources/postgresql/empty.sh
remove the password from environment to reduce risk of exposure to other users and processes, and avoid possibly conflicting passwords
> pgpassword security and conflict avoidance
